// Mocks generated by Mockito from annotations
// in coalnexus/test/features/inspections/presentation/pages/create_inspection_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:coalnexus/features/mines/domain/entities/mine.dart' as _i4;
import 'package:coalnexus/features/mines/domain/usecases/get_cached_mines.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetCachedMines].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCachedMines extends _i1.Mock implements _i2.GetCachedMines {
  @override
  _i3.Future<List<_i4.Mine>> call() => (super.noSuchMethod(
    Invocation.method(#call, []),
    returnValue: _i3.Future<List<_i4.Mine>>.value(<_i4.Mine>[]),
    returnValueForMissingStub: _i3.Future<List<_i4.Mine>>.value(<_i4.Mine>[]),
  ) as _i3.Future<List<_i4.Mine>>);
}
