// Mocks generated by Mockito from annotations
// in coalnexus/test/features/offline/offline_workflow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i2;

import 'package:coalnexus/core/network/connectivity_service.dart' as _i5;
import 'package:coalnexus/core/sync/domain/entities/audit_trail.dart' as _i11;
import 'package:coalnexus/core/sync/domain/repositories/audit_repository.dart'
    as _i10;
import 'package:coalnexus/core/sync/sync_models.dart' as _i4;
import 'package:coalnexus/core/sync/sync_repository.dart' as _i3;
import 'package:coalnexus/features/inspections/data/datasources/inspection_local_data_source.dart'
    as _i6;
import 'package:coalnexus/features/inspections/domain/entities/inspection.dart'
    as _i7;
import 'package:coalnexus/features/inspections/domain/entities/inspection_finding.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SyncRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncRepository extends _i1.Mock implements _i3.SyncRepository {
  MockSyncRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> enqueue(_i4.SyncQueueItem? item) => (super.noSuchMethod(
    Invocation.method(#enqueue, [item]),
    returnValue: _i2.Future<void>.value(),
    returnValueForMissingStub: _i2.Future<void>.value(),
  ) as _i2.Future<void>);

  @override
  _i2.Future<List<_i4.SyncQueueItem>> getPendingOperations() =>
      (super.noSuchMethod(
        Invocation.method(#getPendingOperations, []),
        returnValue: _i2.Future<List<_i4.SyncQueueItem>>.value(
          <_i4.SyncQueueItem>[],
        ),
      ) as _i2.Future<List<_i4.SyncQueueItem>>);

  @override
  _i2.Future<void> updateStatus(
    String? localId,
    _i4.SyncStatus? status, {
    String? lastError,
    int? retryCount,
  }) => (super.noSuchMethod(
    Invocation.method(
      #updateStatus,
      [localId, status],
      {#lastError: lastError, #retryCount: retryCount},
    ),
    returnValue: _i2.Future<void>.value(),
    returnValueForMissingStub: _i2.Future<void>.value(),
  ) as _i2.Future<void>);

  @override
  _i2.Future<void> markSynced(String? localId, String? serverId) =>
      (super.noSuchMethod(
        Invocation.method(#markSynced, [localId, serverId]),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> reconcileServerId(
    String? feature,
    String? localId,
    String? serverId,
  ) => (super.noSuchMethod(
    Invocation.method(#reconcileServerId, [feature, localId, serverId]),
    returnValue: _i2.Future<void>.value(),
    returnValueForMissingStub: _i2.Future<void>.value(),
  ) as _i2.Future<void>);

  @override
  _i2.Future<String?> getServerId(String? feature, String? localId) =>
      (super.noSuchMethod(
        Invocation.method(#getServerId, [feature, localId]),
        returnValue: _i2.Future<String?>.value(),
      ) as _i2.Future<String?>);

  @override
  _i2.Future<void> clearFailedOperations() => (super.noSuchMethod(
    Invocation.method(#clearFailedOperations, []),
    returnValue: _i2.Future<void>.value(),
    returnValueForMissingStub: _i2.Future<void>.value(),
  ) as _i2.Future<void>);

  @override
  _i2.Future<_i4.SyncQueueItem?> getSyncItemByLocalId(String? localId) =>
      (super.noSuchMethod(
        Invocation.method(#getSyncItemByLocalId, [localId]),
        returnValue: _i2.Future<_i4.SyncQueueItem?>.value(),
      ) as _i2.Future<_i4.SyncQueueItem?>);

  @override
  _i2.Future<bool> hasPendingMutations(String? localId) => (super.noSuchMethod(
    Invocation.method(#hasPendingMutations, [localId]),
    returnValue: _i2.Future<bool>.value(false),
  ) as _i2.Future<bool>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i5.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<bool> get isConnected => (super.noSuchMethod(
    Invocation.getter(#isConnected),
    returnValue: _i2.Future<bool>.value(false),
  ) as _i2.Future<bool>);

  @override
  _i2.Stream<bool> get onConnectivityChanged => (super.noSuchMethod(
    Invocation.getter(#onConnectivityChanged),
    returnValue: _i2.Stream<bool>.empty(),
  ) as _i2.Stream<bool>);
}

/// A class which mocks [InspectionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInspectionLocalDataSource extends _i1.Mock
    implements _i6.InspectionLocalDataSource {
  MockInspectionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> saveInspection(_i7.Inspection? inspection) =>
      (super.noSuchMethod(
        Invocation.method(#saveInspection, [inspection]),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> updateInspection(_i7.Inspection? inspection) =>
      (super.noSuchMethod(
        Invocation.method(#updateInspection, [inspection]),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<List<_i7.Inspection>> getAllInspections() => (super.noSuchMethod(
    Invocation.method(#getAllInspections, []),
    returnValue: _i2.Future<List<_i7.Inspection>>.value(<_i7.Inspection>[]),
  ) as _i2.Future<List<_i7.Inspection>>);

  @override
  _i2.Future<_i7.Inspection?> getInspectionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#getInspectionById, [id]),
        returnValue: _i2.Future<_i7.Inspection?>.value(),
      ) as _i2.Future<_i7.Inspection?>);

  @override
  _i2.Future<void> saveFinding(_i8.InspectionFinding? finding) =>
      (super.noSuchMethod(
        Invocation.method(#saveFinding, [finding]),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<List<_i8.InspectionFinding>> getFindingsForInspection(
    String? inspectionId,
  ) => (super.noSuchMethod(
    Invocation.method(#getFindingsForInspection, [inspectionId]),
    returnValue: _i2.Future<List<_i8.InspectionFinding>>.value(
      <_i8.InspectionFinding>[],
    ),
  ) as _i2.Future<List<_i8.InspectionFinding>>);

  @override
  _i2.Future<_i8.InspectionFinding?> getFindingById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#getFindingById, [id]),
        returnValue: _i2.Future<_i8.InspectionFinding?>.value(),
      ) as _i2.Future<_i8.InspectionFinding?>);

  @override
  _i2.Future<void> updateFinding(_i8.InspectionFinding? finding) =>
      (super.noSuchMethod(
        Invocation.method(#updateFinding, [finding]),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(#transaction, [action]),
        returnValue:
            _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(#transaction, [action]),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(this, Invocation.method(#transaction, [action])),
      ) as _i2.Future<T>);
}

/// A class which mocks [AuditRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditRepository extends _i1.Mock implements _i10.AuditRepository {
  MockAuditRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> logAction({
    required String? entityType,
    required String? entityId,
    required String? action,
    String? previousState,
    required String? newState,
    String? comment,
  }) => (super.noSuchMethod(
    Invocation.method(#logAction, [], {
      #entityType: entityType,
      #entityId: entityId,
      #action: action,
      #previousState: previousState,
      #newState: newState,
      #comment: comment,
    }),
    returnValue: _i2.Future<void>.value(),
    returnValueForMissingStub: _i2.Future<void>.value(),
  ) as _i2.Future<void>);

  @override
  _i2.Future<List<_i11.AuditTrail>> getAuditTrail(String? entityId) =>
      (super.noSuchMethod(
        Invocation.method(#getAuditTrail, [entityId]),
        returnValue: _i2.Future<List<_i11.AuditTrail>>.value(
          <_i11.AuditTrail>[],
        ),
      ) as _i2.Future<List<_i11.AuditTrail>>);
}
