// Mocks generated by Mockito from annotations
// in coalnexus/test/features/violations/violation_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:coalnexus/core/sync/outbox_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OutboxService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOutboxService extends _i1.Mock implements _i2.OutboxService {
  MockOutboxService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> enqueueOperation({
    required String? featureName,
    required String? actionType,
    required String? payloadJson,
    String? localId,
  }) => (super.noSuchMethod(
    Invocation.method(#enqueueOperation, [], {
      #featureName: featureName,
      #actionType: actionType,
      #payloadJson: payloadJson,
      #localId: localId,
    }),
    returnValue: _i3.Future<String>.value(
      _i4.dummyValue<String>(
        this,
        Invocation.method(#enqueueOperation, [], {
          #featureName: featureName,
          #actionType: actionType,
          #payloadJson: payloadJson,
          #localId: localId,
        }),
      ),
    ),
  ) as _i3.Future<String>);
}
