"""Initial schema with RBAC and PostGIS

Revision ID: 6077c03fb3c5
Revises: 
Create Date: 2026-09-26 15:17:53.367714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6077c03fb3c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trails',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_audit_trails_id'), 'audit_trails', ['id'], unique=False)
    op.create_index(op.f('ix_audit_trails_local_id'), 'audit_trails', ['local_id'], unique=True)
    op.create_table('evidence',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_local_id'), 'evidence', ['local_id'], unique=True)
    op.create_table('mines',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mine_code', sa.String(), nullable=False),
    sa.Column('company', sa.String(), server_default='WCL', nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mine_code'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_mines_id'), 'mines', ['id'], unique=False)
    op.create_index(op.f('ix_mines_local_id'), 'mines', ['local_id'], unique=True)
    op.create_table('processed_operations',
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_index(op.f('ix_processed_operations_operation_id'), 'processed_operations', ['operation_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='INSPECTOR', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_local_id'), 'alerts', ['local_id'], unique=True)
    op.create_table('inspections',
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('inspector_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('category', sa.String(), server_default='other', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_index(op.f('ix_inspections_local_id'), 'inspections', ['local_id'], unique=True)
    op.create_table('mine_sensors',
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('sensor_code', sa.String(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id'),
    sa.UniqueConstraint('sensor_code')
    )
    op.create_index(op.f('ix_mine_sensors_id'), 'mine_sensors', ['id'], unique=False)
    op.create_index(op.f('ix_mine_sensors_local_id'), 'mine_sensors', ['local_id'], unique=True)
    op.create_table('risk_scores',
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('contributing_factors', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_risk_scores_local_id'), 'risk_scores', ['local_id'], unique=True)
    op.create_table('telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('readings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_table('user_mine_assignments',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'mine_id')
    )
    op.create_table('inspection_findings',
    sa.Column('inspection_id', sa.String(), nullable=False),
    sa.Column('requirement_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), server_default='medium', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_inspection_findings_id'), 'inspection_findings', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_findings_local_id'), 'inspection_findings', ['local_id'], unique=True)
    op.create_table('violations',
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('inspection_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_violations_id'), 'violations', ['id'], unique=False)
    op.create_index(op.f('ix_violations_local_id'), 'violations', ['local_id'], unique=True)
    op.create_table('corrective_actions',
    sa.Column('violation_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_corrective_actions_id'), 'corrective_actions', ['id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_local_id'), 'corrective_actions', ['local_id'], unique=True)
    op.create_table('verification_records',
    sa.Column('corrective_action_id', sa.String(), nullable=False),
    sa.Column('verifier_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('local_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['corrective_action_id'], ['corrective_actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_verification_records_id'), 'verification_records', ['id'], unique=False)
    op.create_index(op.f('ix_verification_records_local_id'), 'verification_records', ['local_id'], unique=True)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_verification_records_local_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_corrective_actions_local_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_violations_local_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_inspection_findings_local_id'), table_name='inspection_findings')
    op.drop_index(op.f('ix_inspection_findings_id'), table_name='inspection_findings')
    op.drop_table('inspection_findings')
    op.drop_table('user_mine_assignments')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_risk_scores_local_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_mine_sensors_local_id'), table_name='mine_sensors')
    op.drop_index(op.f('ix_mine_sensors_id'), table_name='mine_sensors')
    op.drop_table('mine_sensors')
    op.drop_index(op.f('ix_inspections_local_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_alerts_local_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_processed_operations_operation_id'), table_name='processed_operations')
    op.drop_table('processed_operations')
    op.drop_index(op.f('ix_mines_local_id'), table_name='mines')
    op.drop_index(op.f('ix_mines_id'), table_name='mines')
    op.drop_index('idx_mines_location', table_name='mines', postgresql_using='gist')
    op.drop_table('mines')
    op.drop_index(op.f('ix_evidence_local_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_trails_local_id'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_id'), table_name='audit_trails')
    op.drop_table('audit_trails')
    # ### end Alembic commands ###
