// Mocks generated by Mockito from annotations
// in coalnexus/test/features/violations/presentation/pages/violation_pages_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:coalnexus/features/violations/domain/entities/violation.dart'
    as _i5;
import 'package:coalnexus/features/violations/domain/repositories/violation_repository.dart'
    as _i2;
import 'package:coalnexus/features/violations/domain/usecases/create_violation.dart'
    as _i6;
import 'package:coalnexus/features/violations/domain/usecases/get_violation_by_id.dart'
    as _i3;
import 'package:coalnexus/features/violations/domain/usecases/update_violation.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeViolationRepository_0 extends _i1.SmartFake
    implements _i2.ViolationRepository {
  _FakeViolationRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetViolationById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetViolationById extends _i1.Mock implements _i3.GetViolationById {
  @override
  _i2.ViolationRepository get repository => (super.noSuchMethod(
    Invocation.getter(#repository),
    returnValue: _FakeViolationRepository_0(
      this,
      Invocation.getter(#repository),
    ),
    returnValueForMissingStub: _FakeViolationRepository_0(
      this,
      Invocation.getter(#repository),
    ),
  ) as _i2.ViolationRepository);

  @override
  _i4.Future<_i5.Violation?> call(String? id) => (super.noSuchMethod(
    Invocation.method(#call, [id]),
    returnValue: _i4.Future<_i5.Violation?>.value(),
    returnValueForMissingStub: _i4.Future<_i5.Violation?>.value(),
  ) as _i4.Future<_i5.Violation?>);
}

/// A class which mocks [CreateViolation].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateViolation extends _i1.Mock implements _i6.CreateViolation {
  @override
  _i2.ViolationRepository get repository => (super.noSuchMethod(
    Invocation.getter(#repository),
    returnValue: _FakeViolationRepository_0(
      this,
      Invocation.getter(#repository),
    ),
    returnValueForMissingStub: _FakeViolationRepository_0(
      this,
      Invocation.getter(#repository),
    ),
  ) as _i2.ViolationRepository);

  @override
  _i4.Future<void> call(_i5.Violation? violation) => (super.noSuchMethod(
    Invocation.method(#call, [violation]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}

/// A class which mocks [UpdateViolation].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateViolation extends _i1.Mock implements _i7.UpdateViolation {
  @override
  _i2.ViolationRepository get repository => (super.noSuchMethod(
    Invocation.getter(#repository),
    returnValue: _FakeViolationRepository_0(
      this,
      Invocation.getter(#repository),
    ),
    returnValueForMissingStub: _FakeViolationRepository_0(
      this,
      Invocation.getter(#repository),
    ),
  ) as _i2.ViolationRepository);

  @override
  _i4.Future<void> call(_i5.Violation? violation) => (super.noSuchMethod(
    Invocation.method(#call, [violation]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}
